# Generated by Django 3.2.20 on 2023-12-11 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0004_gstr3b'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gstr3B',
        ),
    ]
